
version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" 
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - BACKEND_PORT=3001 
      - FRONTEND_URL=http://frontend:3000 
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3001 